### ISSUE TITLE
Re. MialSRTK usage

### ISSUE THREAD

**Issue by amitjc** [Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit#101]
Dear Experts,

I look forward to working with MialSRTK for fetal super-resolution MRI.

However, I run into error while running mialsrtk with or without wrappers. Please find the error code attached below. Also attaching the params and imaging files.

I request guidance for the issue.

Thank you.

Best Regards,
Amit.

```
docker run -t --rm -u $(id -u):$(id -g) -v /path/to/FetalMRI/BIDS/sub-1/anat:/bids_dir -v /path/to/FetalMRI/BIDS/derivatives:/output_dir sebastientourbier/mialsuperresolutiontoolkit /bids_dir /output_dir participant
id: : no such user
User:
id: : no such user
Group:
declare -x BIN_DIR="/usr/local/bin"
declare -x CONDA_ACTIVATE="source /opt/conda/bin/activate pymialsrtk-env"
declare -x CONDA_ENV_PATH="/opt/conda"
declare -x DISPLAY=":0"
declare -x GLIBCPP_FORCE_NEW="1"
declare -x GLIBCXX_FORCE_NEW="1"
declare -x HOME="/home/mialsrtk"
declare -x HOSTNAME="756a80a0007e"
declare -x LANG="C.UTF-8"
declare -x LC_ALL="C.UTF-8"
declare -x LD_PRELOAD="/usr/lib/libtcmalloc.so.4"
declare -x MY_CONDA_PY3ENV="pymialsrtk-env"
declare -x OLDPWD
declare -x PATH="/usr/local/bin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
declare -x PWD="/app"
declare -x SHLVL="1"
declare -x TERM="xterm"
SHELL: /bin/sh
PATH: /usr/local/bin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-oxp0f0k4 because the default path (/home/mialsrtk/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
WARNING:tensorflow:From /opt/conda/envs/pymialsrtk-env/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
INFO: Number of cores used by Nipype engine set to 2
INFO: Environment variable OMP_NUM_THREADS set to: 2
/bids_dir/code/participants_params.json
{'participant_id': {'Description': 'Unique participant identifier'}, 'age': {'LongName': 'Long (unabbreviated) name of the column', 'Description': 'Description of the the column', 'Levels': {'Key': 'Value (This is for categorical variables: a dictionary of possible values (keys) and their descriptions (values))'}, 'Units': 'Measurement units. [<prefix symbol>]<unit symbol> format following the SI standard is RECOMMENDED'}, 'sex': {'LongName': 'Long (unabbreviated) name of the column', 'Description': 'Description of the the column', 'Levels': {'Key': 'Value (This is for categorical variables: a dictionary of possible values (keys) and their descriptions (values))'}, 'Units': 'Measurement units. [<prefix symbol>]<unit symbol> format following the SI standard is RECOMMENDED'}, 'size': {'LongName': 'Long (unabbreviated) name of the column', 'Description': 'Description of the the column', 'Levels': {'Key': 'Value (This is for categorical variables: a dictionary of possible values (keys) and their descriptions (values))'}, 'Units': 'Measurement units. [<prefix symbol>]<unit symbol> format following the SI standard is RECOMMENDED'}, 'weight': {'LongName': 'Long (unabbreviated) name of the column', 'Description': 'Description of the the column', 'Levels': {'Key': 'Value (This is for categorical variables: a dictionary of possible values (keys) and their descriptions (values))'}, 'Units': 'Measurement units. [<prefix symbol>]<unit symbol> format following the SI standard is RECOMMENDED'}}
dict_keys(['participant_id', 'age', 'sex', 'size', 'weight'])

Traceback (most recent call last):
  File "/opt/mialsuperresolutiontoolkit/docker/bidsapp/run.py", line 247, in <module>
    if len(args.participant_label) >= 1:
TypeError: object of type 'NoneType' has no len()
```

[participants_params.txt](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/files/6290381/participants_params.txt)
[sub-1_acq-AXSSFSEBH_run-1_T2w.nii.gz](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/files/6290386/sub-1_acq-AXSSFSEBH_run-1_T2w.nii.gz)

[sub-1_acq-AXSSFSEBH_run-2_T2w.nii.gz](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/files/6290389/sub-1_acq-AXSSFSEBH_run-2_T2w.nii.gz)
[sub-1_acq-CorSSFSEBH_run-1_T2w.nii.gz](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/files/6290390/sub-1_acq-CorSSFSEBH_run-1_T2w.nii.gz)
[sub-1_acq-SAGSSFSEBH_run-1_T2w.nii.gz](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/files/6290392/sub-1_acq-SAGSSFSEBH_run-1_T2w.nii.gz)
[sub-1_acq-SAGSSFSEBH_run-2_T2w.nii.gz](https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/files/6290393/sub-1_acq-SAGSSFSEBH_run-2_T2w.nii.gz)

**Comment by amitjc** [comment]
Issues, when run with wrapper:

```
mialsuperresolutiontoolkit_docker /mnt/d/NANAVATI_CASES/FetalMRI/BIDS /mnt/d/NANAVATI_CASES/FetalMRI/BIDS/derivatives participant
Traceback (most recent call last):
  File "/home/amitjc/.local/bin/mialsuperresolutiontoolkit_docker", line 11, in <module>
    load_entry_point('pymialsrtk', 'console_scripts', 'mialsuperresolutiontoolkit_docker')()
  File "/home/amitjc/src/pymialsrtk/pymialsrtk/cli/mialsuperresolutiontoolkit_docker.py", line 88, in main
    cmd = create_docker_cmd(args)
  File "/home/amitjc/src/pymialsrtk/pymialsrtk/cli/mialsuperresolutiontoolkit_docker.py", line 58, in create_docker_cmd
    for label in args.participant_label:
TypeError: 'NoneType' object is not iterable
```

**Comment by sebastientourbier** [comment]
Hi @amitjc!

Thanks for bringing this!

I see here multiple reasons:

1. It is strongly recommended to have labels sub-01, sub-02, sub-03

2. There is a little mistake in the command that should be:
   ```
   docker run -t --rm -u $(id -u):$(id -g) -v /path/to/FetalMRI/BIDS:/bids_dir -v /path/to/FetalMRI/BIDS/derivatives:/output_dir   sebastientourbier/mialsuperresolutiontoolkit /bids_dir /output_dir participant 
   ```  
where the the root directory of the BIDS dataset is mapped to `/bids_dir`.

3. You spot a bug :) It seems we are not handling this as it should be for running all subjects. We will review it for the new release. In the meantime you would have to set explicitly the subjects with the `--participant_label` option. The previous command will look like:
   ```
   docker run -t --rm -u $(id -u):$(id -g) -v /path/to/FetalMRI/BIDS:/bids_dir -v /path/to/FetalMRI/BIDS/derivatives:/output_dir   sebastientourbier/mialsuperresolutiontoolkit:v2.0.1 /bids_dir /output_dir participant --participant_label 01 02 [...]
   ```  
where I also specified explicitly the version of mialsuperresolutiontoolkit. Doing so, one is guaranteed to use the same version in an analysis.

4. To specify different parameters of the pipeline you will have to create a configuration file `participants_params.json` in the `/path/to/BIDSDir/code` folder that follows the structure described at https://mialsrtk.readthedocs.io/en/latest/usage.html#bids-app-configuration-file. Then you could use it by calling the BIDS app as in the following:
   ```
   docker run -t --rm -u $(id -u):$(id -g) -v /path/to/FetalMRI/BIDS:/bids_dir -v /path/to/FetalMRI/BIDS/derivatives:/output_dir   sebastientourbier/mialsuperresolutiontoolkit:v2.0.1 /bids_dir /output_dir participant --participant_label 01 02 [...] --param_file /bids_dir/code/participants_params.json
   ```  

Hope this helps

**Comment by amitjc** [comment]
Dear Sir,

Thank you for the response.

Based on your inputs, the participants_params.json needs to be generated as per the description at the recommended link.

I’ll be highly obliged if you can guide me further for generating the necessary participants_params.json...eg., a script which can generate this file from the subject nifti and json sidecar.

Best Regards,
Amit.
