### ISSUE TITLE
BUG: TV Super Resolution Node crashes with segmentation fault

### ISSUE THREAD

**Issue by pdedumast** [Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit#107]
See trace below. 
Note that `--nipype_nb_of_cores` and `--openmp_nb_of_cores` parameters not specified, and SR image is well computed and saved.

```##########################################################################################################
Inner loop optimization took 96.245 (Unix time)
##########################################################################################################

Writing /output_dir/nipype-1.6.0/sub-ctrl0038/ses-20180912073131/rec-3/srr_pipeline/srtkTVSuperResolution/SRTV_sub-ctrl0038_ses-20180912073131_6V_rad1.nii.gz ... done.
  > Write JSON side-car...
  > Load SR image /output_dir/nipype-1.6.0/sub-ctrl0038/ses-20180912073131/rec-3/srr_pipeline/srtkTVSuperResolution/SRTV_sub-ctrl0038_ses-20180912073131_6V_rad1.nii.gz...
    Image properties: Zooms=(1.125, 1.125, 1.125)/ Shape=(320, 320, 94)/ FOV=[360.   360.   105.75]/ middle cut=[160, 160, 47]
  > Crop SR image at (100:220, 100:220, 0:-1)...
Fatal Python error: Segmentation fault

Current thread 0x00007f0a56ad1780 (most recent call first):
  File "/opt/conda/envs/pymialsrtk-env/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 1456 in eigh
  File "/opt/conda/envs/pymialsrtk-env/lib/python3.7/site-packages/nibabel/quaternions.py", line 211 in mat2quat
  File "/opt/conda/envs/pymialsrtk-env/lib/python3.7/site-packages/nibabel/nifti1.py", line 1031 in set_qform
  File "/opt/conda/envs/pymialsrtk-env/lib/python3.7/site-packages/nibabel/nifti1.py", line 1817 in _affine2header
  File "/opt/conda/envs/pymialsrtk-env/lib/python3.7/site-packages/nibabel/spatialimages.py", line 503 in update_header
  File "/opt/conda/envs/pymialsrtk-env/lib/python3.7/site-packages/nibabel/nifti1.py", line 1807 in update_header
  File "/opt/conda/envs/pymialsrtk-env/lib/python3.7/site-packages/nibabel/nifti1.py", line 2044 in update_header
  File "/opt/conda/envs/pymialsrtk-env/lib/python3.7/site-packages/nibabel/spatialimages.py", line 469 in __init__
  File "/opt/conda/envs/pymialsrtk-env/lib/python3.7/site-packages/nibabel/analyze.py", line 923 in __init__
  File "/opt/conda/envs/pymialsrtk-env/lib/python3.7/site-packages/nibabel/nifti1.py", line 1772 in __init__
  File "/opt/conda/envs/pymialsrtk-env/lib/python3.7/site-packages/nibabel/spatialimages.py", line 350 in __getitem__
  File "/opt/conda/envs/pymialsrtk-env/lib/python3.7/site-packages/pymialsrtk/interfaces/reconstruction.py", line 422 in _run_interface
  File "/opt/conda/envs/pymialsrtk-env/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 434 in run
  File "/opt/conda/envs/pymialsrtk-env/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741 in _run_command
  File "/opt/conda/envs/pymialsrtk-env/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635 in _run_interface
  File "/opt/conda/envs/pymialsrtk-env/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516 in run
  File "/opt/conda/envs/pymialsrtk-env/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67 in run_node
  File "/opt/conda/envs/pymialsrtk-env/lib/python3.7/concurrent/futures/process.py", line 239 in _process_worker
  File "/opt/conda/envs/pymialsrtk-env/lib/python3.7/multiprocessing/process.py", line 99 in run
  File "/opt/conda/envs/pymialsrtk-env/lib/python3.7/multiprocessing/process.py", line 297 in _bootstrap
  File "/opt/conda/envs/pymialsrtk-env/lib/python3.7/multiprocessing/popen_fork.py", line 74 in _launch
  File "/opt/conda/envs/pymialsrtk-env/lib/python3.7/multiprocessing/popen_fork.py", line 20 in __init__
  File "/opt/conda/envs/pymialsrtk-env/lib/python3.7/multiprocessing/context.py", line 277 in _Popen
  File "/opt/conda/envs/pymialsrtk-env/lib/python3.7/multiprocessing/process.py", line 112 in start
  File "/opt/conda/envs/pymialsrtk-env/lib/python3.7/concurrent/futures/process.py", line 607 in _adjust_process_count
  File "/opt/conda/envs/pymialsrtk-env/lib/python3.7/concurrent/futures/process.py", line 583 in _start_queue_management_thread
  File "/opt/conda/envs/pymialsrtk-env/lib/python3.7/concurrent/futures/process.py", line 641 in submit
  File "/opt/conda/envs/pymialsrtk-env/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 175 in _submit_job
  File "/opt/conda/envs/pymialsrtk-env/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 367 in _send_procs_to_workers
  File "/opt/conda/envs/pymialsrtk-env/lib/python3.7/site-packages/nipype/pipeline/plugins/base.py", line 184 in run
  File "/opt/conda/envs/pymialsrtk-env/lib/python3.7/site-packages/nipype/pipeline/engine/workflows.py", line 632 in run
  File "/opt/conda/envs/pymialsrtk-env/lib/python3.7/site-packages/pymialsrtk/pipelines/anatomical/srr.py", line 679 in run
  File "/opt/mialsuperresolutiontoolkit/docker/bidsapp/run.py", line 235 in main
  File "/opt/mialsuperresolutiontoolkit/docker/bidsapp/run.py", line 306 in <module>
exception calling callback for <Future at 0x7f09e1868a10 state=finished raised BrokenProcessPool>
Traceback (most recent call last):
  File "/opt/conda/envs/pymialsrtk-env/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/opt/conda/envs/pymialsrtk-env/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 159, in _async_callback
    result = args.result()
  File "/opt/conda/envs/pymialsrtk-env/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/opt/conda/envs/pymialsrtk-env/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

**Comment by sebastientourbier** [comment]
Please reopen issue if needed
